{{- if .Values.global.enable.server }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo.name }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.mongo.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.mongo.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongo.name }}
    spec:
      containers:
        - name: {{ .Values.mongo.name }}
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: {{ .Values.mongo.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongo.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongo.password}}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongo.database }}
{{- end }}
