{{- if .Values.global.enable.server }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.namespace }}
spec:
  {{- if eq .Values.global.profile "local" }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      {{- if eq .Values.global.profile "local" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Values.service.name }}
{{- end }}
