# user service
service:
  name: user-application
  image: youdong98/kpring-user-application:latest
  port: 8080
  nodePort: 30002

api:
  authServiceUrl: http://auth-application

mysql:
  name: user-mysql
  image: mysql:8.0
  port: 3306
  rootPassword: root@password1234
  username: local-user
  password: local@password1234
  url: jdbc:mysql://user-mysql:3306/localdb
  dbname: localdb
